spring.application.name=bff

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Microservicios
auth.service.base-url=http://localhost:4004
bike.service.url=http://localhost:4003
customer.service.url=http://localhost:4002
rent.service.url=http://localhost:4001

# JWT: el BFF valida la firma de los tokens usando las llaves públicas (JWKS)
# que expone ms-auth en http://localhost:4004/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${auth.service.base-url}/.well-known/jwks.json