spring.application.name=bff

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=$&miSercreto.SuperSeguro!1988
security.jwt.expiration-hours=24
